### ISSUE TITLE
Compiling code in more than one directory

### ISSUE THREAD

**Issue by ftomassetti** [talios/frege-maven-plugin#2]
Is it possible to specify more than one directory? I would like to compile regular frege code and generated frege code which is stored in a separated directory. Currently I can specify only one source directory, right?

**Comment by talios** [comment]
Currently it's not, but would be fairly trivial to automatically (without even configuring) any target/generated-sources subdirectory as a source directory to also use ( which is java convention ). Then you could just generate into that directory.

I'll look at that tonight.

**Comment by talios** [comment]
I've pushed some changes to the `develop` branch which will now include any/all `target/generated-sources/*` directories during compilation, and `target/generated-test-sources/*` during test compilation.

I tested this locally just manually moving some `.fr` files from my main source directory into a generated one and it appears to work fine.
